<div class="container-fluid bg-light">
  <div class="row d-flex h-100 justify-content-center align-items-center">
    <div class="col-md-4">
      <h1 class="display-4">Area Administrativa!</h1>
      <span class="lead text-warning">Atenção, essa é uma restrita.</span>
    </div>
    <div class="col-md-4">
      <form action="/admin_auth" method="post">
        <div class="form-group">
          <label for="usu">Nome de Usuário</label>
          <input type="text" required name="login" class="form-control" id="usu" placeholder="Nome de Usuário">
        </div>
        <div class="form-group">
          <label for="senha">Senha</label>
          <input type="password" required name="senha" class="form-control" id="senha" placeholder="Senha">
        </div>
        <div class="form-group">
          <label for="toekn">Token de Acesso</label>
          <input type="password" required name="token" class="form-control" id="token" placeholder="Token de Acesso">
        </div>
        <button type="submit" class="btn btn-danger">Enviar</button>
        <a class="btn btn-outline-dark float-right" href="/">Voltar</a>
        <?php if($this->view->erroLogin == 'form_null'){ ?>
          <div class="form-group">
            <span class="text-warning d-block">*Por favor, preencha os campos acima.</span>
          </div>
        <?php } ?>
        <?php if($this->view->erroLogin == 'none_user'){ ?>
          <div class="form-group">
            <span class="text-warning d-block">*Nome de usuário e a senha não combinam.</span>
          </div>
        <?php } ?>
      </form>
    </div>
  </div>
</div>