<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand mr-5" href="#"><img src="imagens/logo-retry.png" width="80"></a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav w-100">
			<li class="nav-item">
				<a class="nav-link" href="/jogos">Jogos</a>
			</li>
			<li class="nav-item dropdown ml-auto"> <!-- ml-md-3 mt-sm-3 mt-md-0 -->
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<?= $this->view->admin ?>
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
					<a class="dropdown-item" href="/admin_sair">Sair</a>
				</div>
			</li>  
		</ul>
	</div>
</nav>
<section class="container-fluid p-0 d-flex justify-content-center pt-5">
<div class="w-75 bg-dark mb-5 ">
        <h1 class="text-center Display-4 text-light p-5 mt-5">Cadastro de Jogos</h1>
        <?php if(isset($this->view->jogo)){ ?>
            <form class="w-75 p-5" action="/alterar?acao=alt&id=<?= $this->view->jogo['id'] ?>" method="post" enctype="multipart/form-data">
        <?php }else{ ?>
            <form class="w-75 p-5" action="/cadJogo?acao=cad" method="post" enctype="multipart/form-data">
        <?php } ?>
       
            <div class="form-group">
                <label for="titulo" class="text-light">Título</label>
                <input type="text" name="titulo" class="form-control" id="titulo" placeholder="Título do jogo" value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['titulo'];
                    } ?>">
            </div>
            <div class="form-group">
                <label for="categoria" class="text-light">Categoria</label>
                <input type="text" name="categoria" class="form-control" id="categoria" placeholder="Categoria do jogo" value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['categoria'];
                    } ?>">
            </div>
            <div class="form-group">
                <label for="criador" class="text-light">Criador</label>
                <input type="text" name="criador" class="form-control" id="criador" placeholder="Criador do Jogo" value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['criador'];
                    } ?>">
            </div>
            <div class="form-group">
                <label for="data_lanc" class="text-light">Data de Lançamento</label>
                <input type="text" name="data_lancamento"value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['data_lancamento'];
                    } ?>" class="form-control" id="data_lanc" placeholder="Ex: 2019-09-20">
            </div>
            <div class="form-group">
                <label for="plataformas" class="text-light">Plataformas</label>
                <input type="text" name="plataformas" class="form-control" id="plataformas" placeholder="Plataformas disponíveis" value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['plataformas'];
                    } ?>">
            </div>
            <div class="form-group">
                <?php if(isset($this->view->jogo)){ ?>
                    <p for="imagem" class="text-light"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['imagem'];
                    } ?></p>
                    <input type="text" name="imagemAnt" value="<?= $this->view->jogo['imagem']; ?>" style="display: none;">
                <?php }else{ ?>
                    <label for="imagem" class="text-light">Imagem</label>
                <?php } ?>
                <input name="imagem" type="file" />
            </div>
            <div class="form-group">
                <?php if(isset($this->view->jogo)){ ?>
                    <p for="imagem" class="text-light"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['imgretrato'];
                    } ?></p>
                    <input type="text" name="imagemRetAnt" value="<?= $this->view->jogo['imgretrato']; ?>" style="display: none;">
                <?php }else{ ?>
                    <label for="imagemret" class="text-light">Imagem Retrato</label>
                <?php } ?>
                <input name="imagemRet" type="file" />
            </div>
            <div class="form-group">
                <label for="video" class="text-light">Video</label>
                <input type="text" name="link_video" class="form-control" id="video" placeholder="Link do video do jogo" value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['link_video'];
                    } ?>">
            </div>
            <div class="form-group">
                <label for="resumo" class="text-light">Resumo</label>
                <textarea name="resumo" class="form-control" id="resumo" placeholder="Resumo do jogo" rows="10"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['resumo'];
                    } ?></textarea>
            </div>
            <div class="form-group">
                <label for="res" class="text-light">Sinopse Resumida</label>
                <textarea name="sinopseResumida" class="form-control" id="res" placeholder="Resumo da sinopse do jogo" rows="10"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['sinopse_resumida'];
                    } ?></textarea>
            </div>
            <div class="form-group">
                <label for="reqmin" class="text-light">Requisitos Minimos</label>
                <textarea name="reqMin" class="form-control" id="reqmin" placeholder="Recsitos minimos do jogo" rows="10"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['requisitos_minimos'];
                    } ?></textarea>
            </div>
            <div class="form-group">
                <label for="reqrec" class="text-light">Requisitos Recomendados</label>
                <textarea name="reqRecomendados" class="form-control" id="reqrec" placeholder="Resumo do jogo" rows="10"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['requisitos_recomendados'];
                    } ?></textarea>
            </div>
            <div class="form-group">
                <label for="avaliacao" class="text-light">Avaliação</label>
                <textarea name="avaliacao" class="form-control" id="avaliacao" placeholder="Avaliação do jogo" rows="10"><?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['avaliacao'];
                    } ?></textarea>
            </div>
            <div class="form-group">
                <label for="nota" class="text-light">Nota</label>
                <input name="nota" type="number" class="form-control" id="nota" placeholder="Nota do jogo" value="<?php 
                    if(isset($this->view->jogo)){
                        echo $this->view->jogo['nota'];
                    } ?>">
            </div>
            <?php if(isset($this->view->jogo)){ ?>
                <button type="submit" class="btn btn-outline-light">Alterar</button>
                <a href="/delJogo?acao=del&id=<?= $this->view->jogo['id'] ?>" class="btn btn-outline-light">Deletar</a> 
            <?php }else{ ?>
                <button type="submit" class="btn btn-outline-light">Cadastrar</button>
            <?php } ?>
        </form>

        <h1 class="text-center Display-4 text-light mb-5">Jogos</h1>
        <table class="table table-dark mb-5">
            <thead>
                <tr>
                <th scope="col">Código</th>
                <th scope="col">Jogo</th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->view->jogos as $key => $jogo) {?>

                    <tr>
                    <th scope="row"><?= $jogo['id'] ?></th>
                    <td><a href="/selJogo?acao=sel&id=<?= $jogo['id'] ?>"><?= $jogo['titulo'] ?></a></td>
                    <td><a href="/altJogo?acao=alt&id=<?= $jogo['id'] ?>"><i class="fas fa-pencil-alt text-light"></i></a></td>
                    <td><a href="/delJogo?acao=del&id=<?= $jogo['id'] ?>"><i class="fas fa-backspace text-light"></i></a></td>
                    </tr>

                <?php } ?>
            </tbody>
        </table>
    </div>
</section>

<style>
    body{
        background-color: #6c757d;
    }
    textarea{
        resize: none;
    }
</style>