<div class="container-fluid">
  <div class="row d-flex h-100 justify-content-center align-items-center">
    <div class="col-md-4">
      <h1 class="display-4">Bem Vindo(a) a <span class="text-danger">Retry</span></h1>
      <span class="lead">Faça sua inscrição para continuar.</span>
    </div>
    <div class="col-md-4">
      <form action="/registrar" method="post"> 
        <div class="form-group">
          <label for="usu">Nome de Usuário</label>
          <?php if($this->view->erroCadastro == 'login_curto'){ ?>
            <small class="text-warning d-block">*Nome de usuário muito curto. (min. 6 carácters)</small>
          <?php } ?>
          <?php if($this->view->erroCadastro == 'login_existente'){ ?>
            <small class="text-warning d-block">*Este nome de usuário já esta em uso.</small>
          <?php } ?>
          <input type="text" name="login" class="form-control" id="usu" placeholder="Nome de Usuário" value="<?= $this->view->dados['login'] ?>" required>
        </div>
        <div class="form-group">
          <label for="senha">Senha</label>
          <?php if($this->view->erroCadastro == 'senha_curta'){ ?>
            <small class="text-warning d-block">*Senha muito curta. (min. 6 carácters)</small>
          <?php } ?>
          <input type="password" name="senha" class="form-control" id="senha" placeholder="Senha" value="<?= $this->view->dados['senha'] ?>" required>
        </div>
        <div class="form-group">
          <label for="email">E-mail</label>
          <?php if($this->view->erroCadastro == 'email_existente'){ ?>
            <small class="text-warning d-block">*Este e-mail já está sendo usado por outro usuário.</small>
          <?php } ?>
          <input type="email" name="email" class="form-control" id="email" placeholder="Seu email" value="<?= $this->view->dados['email'] ?>" required>
        </div>
        <button type="submit" class="btn btn-danger">Enviar</button>
        <a class="btn btn-outline-dark float-right" href="/login">Voltar</a>
      </form>
    </div>
  </div>
</div>